# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-18 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastime', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.TextField(default='my age'),
        ),
    ]
